create_smb_share_data = {
    'cluster': POWERSCALE_CLUSTER_NAME,
    'access_zone': POWERSCALE_ZONE,
    'name': POWERSCALE_NAME,
    'description': POWERSCALE_DESCRIPTION,
    'path': POWERSCALE_PATH,
    'create_smb_share_directory_if_it_does_not_exist': POWERSCALE_CREATE_IF_NOT_EXIST,
    'directory_acls': POWERSCALE_DIR_ACL,
    'allow_variable_expansion': POWERSCALE_ALLOW_VAR_EXP,
    'continuous_availability': POWERSCALE_ENABLE_CONTINUOUS_AVAILABILITY,
    'read_only_users': POWERSCALE_RO_USERS,
    'read_write_users': POWERSCALE_RW_USERS,
    'full_control_users': POWERSCALE_FC_USERS,
    'root_users': POWERSCALE_RT_USERS,
    'read_only_groups': POWERSCALE_RO_GROUPS,
    'read_write_groups': POWERSCALE_RW_GROUPS,
    'full_control_groups': POWERSCALE_FC_GROUPS,
    'root_groups': POWERSCALE_RT_GROUPS,
    'read_only_well_known_sids': POWERSCALE_RO_WELLKNOWNS,
    'read_write_well_known_sids': POWERSCALE_RW_WELLKNOWNS,
    'full_control_well_known_sids': POWERSCALE_FC_WELLKNOWNS,
    'root_well_known_sids': POWERSCALE_RT_WELLKNOWNS,
    'enable_file_filters': POWERSCALE_ENABLE_FILE_FILTERS,
}