add_new_esxi_host_to_esxi_cluster_data = {
    'powermax_array': POWERMAX_POWER_MAX_ARRAY,
    'esxi_host': POWERMAX_ESXI_HOST,
    'host_name': POWERMAX_HOST_NAME,
    'initiators_of_the_esxi_host': POWERMAX_AVAILABLE_INITIATORS,
    'reuse_existing_host_entry_if_an_acceptable_match_is_found': POWERMAX_REUSE_IF_MATCH_FOUND,
    'scsi_support1_powermax_host_flag': POWERMAX_SCSI_SUPPORT1,
    'avoid_reset_broadcast_powermax_host_flag': POWERMAX_AVOID_RESET_BROADCAST,
    'volume_set_addressing_powermax_host_flag': POWERMAX_VOLUME_SET_ADDRESSING,
    'disable_q_reset_on_ua_powermax_host_flag': POWERMAX_DISABLE_Q_RESET_ON_UA,
    'spc2_protocol_version_powermax_host_flag': POWERMAX_SPC2_PROTOCOL_VERSION,
    'scsi3_powermax_host_flag': POWERMAX_SCSI3,
    'environ_set_powermax_host_flag': POWERMAX_ENVIRON_SET,
    'open_vms_powermax_host_flag': POWERMAX_OPEN_VMS,
    'consistent_luns_powermax_host_flag': POWERMAX_CONSISTENT_LUN,
    'esxi_cluster': POWERMAX_ESXI_CLUSTER,
    'host_group': POWERMAX_HOST_GROUP,
}