suspend_srdf_protection_data = {
    'powermax_array': POWERMAX_POWER_MAX_ARRAY,
    'storage_group': POWERMAX_STORAGE_GROUP,
    'the_storage_group_rdf_group': POWERMAX_STORAGE_GROUP_RDF_GROUP,
    'bypass_flag:_bypasses_any_existing_powermax_exclusive_locks_during_an_srdf_operation._warning:_only_use_this_flag_if_you_are_certain_no_other_srdf_operation_is_in_progress_at_the_local_and/or_remote_powermax_arrays.': POWERMAX_BYPASS,
    'metro_bias_flag:__when_the_srdf_is_set_to_active,_this_specifies_to_move_the_bias_to_the_r2_powermax': POWERMAX_METRO_BIAS,
    'immediate_flag:_applies_only_to_srdf/asynchronous_capable_devices._causes_command_to_drop_the_srdf/a_session_immediately.': POWERMAX_IMMEDIATE,
    'consistency_exempt_flag:__	allows_devices_to_be_suspended_without_affecting_the_state_of_the_srdf/a_session_or_requiring_that_other_devices_in_the_session_be_suspended._used_for_an_srdf_group_supporting_an_active_srdf/a_session.': POWERMAX_CONSISTENCY_EXEMPT,
}