create_nfs_export_data = {
    'cluster': POWERSCALE_CLUSTER,
    'access_zone': POWERSCALE_ZONE,
    'use_nfs_alias': POWERSCALE_USING_ALIAS,
    'directory_path_(specify_the_path_under_zone_base_path_that_is_exported)': POWERSCALE_PATH,
    'description_of_the_export': POWERSCALE_DESCRIPTION,
    'clients_to_be_allowed_access_to_the_export': POWERSCALE_CLIENTS,
    'clients_to_be_allowed_read_write_access_to_the_export': POWERSCALE_READ_WRITE_CLIENTS,
    'clients_to_be_allowed_read_only_access_to_the_export': POWERSCALE_READ_ONLY_CLIENTS,
    'clients_that_have_root_access_to_the_export': POWERSCALE_ROOT_CLIENTS,
    'restrict_export_access_to_read_only': POWERSCALE_IS_READ_ONLY,
    'enable_mount_access_to_subdirectories': POWERSCALE_MOUNT_SUB_DIRS,
    'use_default_value_for_root_user_mapping': POWERSCALE_USE_DEFAULT_ROOT_MAPPING,
    'use_default_value_for_non_root_user_mapping': POWERSCALE_USE_DEFAULT_NON_ROOT_MAPPING,
    'use_default_value_for_failed_user_mapping': POWERSCALE_USE_DEFAULT_FAILED_MAPPING,
    'use_default_security_types': POWERSCALE_USE_DEFAULT_SECURITY_TYPES,
    'mount_export_to_linux_vms': POWERSCALE_MOUNT,
    'linux_hosts_that_will_mount_the_created_nfs_export': POWERSCALE_SSH_HOST_LIST,
    'do_you_want_to_use_password_authentication?_if_unchecked,_public_key_authentication_will_be_used.': POWERSCALE_PASSWORD_AUTHENTICATION,
    'passwords_of_the_registered_ssh_hosts': POWERSCALE_PASSWORDS,
    'nfs_server_ip_to_mount_the_export._(note_the_ip_might_vary_depending_on_the_access_zone_the_export_belongs_to.)': POWERSCALE_NFS_SERVER_IP,
    'mount_point': POWERSCALE_MOUNT_POINT,
    'unmount_already_mounted_path': POWERSCALE_UNMOUNT,
    'nfs_protocol_version_for_mounting': POWERSCALE_NFS_VERSION,
}