modify_nfs_export_data = {
    'cluster': POWERSCALE_CLUSTER,
    'access_zone': POWERSCALE_ZONE,
    'nfs_export_paths_information': POWERSCALE_PATHS_INFO,
    'nfs_export_id': POWERSCALE_ID,
    'description_of_the_export': POWERSCALE_DESCRIPTION,
    'clients_to_be_allowed_access_to_the_export': POWERSCALE_CLIENTS,
    'clients_to_be_allowed_read_write_access_to_the_export': POWERSCALE_READ_WRITE_CLIENTS,
    'clients_to_be_allowed_read_only_access_to_the_export': POWERSCALE_READ_ONLY_CLIENTS,
    'clients_that_have_root_access_to_the_export': POWERSCALE_ROOT_CLIENTS,
    'restrict_export_access_to_read_only': POWERSCALE_IS_READ_ONLY,
    'enable_mount_access_to_subdirectories': POWERSCALE_MOUNT_SUB_DIRS,
    'enable_root_users_mapping': POWERSCALE_MAP_ROOT_USERS,
    'enable_non_root_users_mapping': POWERSCALE_MAP_NON_ROOT_USERS,
    'enable_failed_users_mapping': POWERSCALE_MAP_FAILED_USERS,
    'security_types': POWERSCALE_SECURITY_TYPES,
}